# Generated by Django 5.2.11 on 2026-03-11 04:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("EmployeeAttendance", "0002_employee_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceLocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "attendance_type",
                    models.CharField(
                        choices=[
                            ("morning_in", "Morning In"),
                            ("morning_out", "Morning Out"),
                            ("afternoon_in", "Afternoon In"),
                            ("afternoon_out", "Afternoon Out"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("recorded_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_logs",
                        to="EmployeeAttendance.attendance",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_locations",
                        to="EmployeeAttendance.employee",
                    ),
                ),
            ],
            options={"ordering": ["-recorded_at"]},
        ),
    ]
